version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: 'mysql_service'
    environment:
      MYSQL_DATABASE: 'public'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root-password'
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - mysql_net
volumes:
  mysql_volume:
networks:
  mysql_net:
