version: '3.2'
services:
  rabbitmq:
    # Where we tell Docker which image to pull.
    image: rabbitmq:3.12.6-management-alpine
    restart: always
    # Represents the container created from the image
    container_name: 'rabbitmq'
    ports:
      # The list of ports that will be mapped from the container to the outside world
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_volume:/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbitmq_volume:/rabbitmq/log/:/var/log/rabbitmq
      # Where we specify the network's name that the container will be using.
    networks:
      - rabbitmq_go_net
volumes:
  rabbitmq_volume:
networks:
  rabbitmq_go_net:
    driver: bridge
