version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12.6-management-alpine
    restart: always
    container_name: 'rabbitmq_service'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_volume:/rabbitmq/data/:/var/lib/rabbitmq
      - rabbitmq_volume:/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
volumes:
  rabbitmq_volume:
networks:
  rabbitmq_net:
